import com.nitin.activemq.activemqeaxample.model;
import java.util.*;

global java.lang.String serviceName;
dialect  "mvel"

rule "Determine Service Scenario 1"

when
	seoEventInstance:SeoEvent(MessageTypeEnum.ASPECT == messageType);
then
	serviceName="Service1";

end

rule "Determine Service Scenario 2"
	
when
	seoEventInstance:SeoEvent(MessageTypeEnum.AUDIT == messageType);
then
	serviceName="Service2";	

end

rule "Determine Service Scenario 3"	

when
	seoEventInstance:SeoEvent(MessageTypeEnum.EVENT == messageType);
then
	serviceName="Service3";	

end

rule "Determine Service Scenario 4"	

when
	seoEventInstance:SeoEvent(MessageTypeEnum.EXCEPTION == messageType);
then
	serviceName="Service3";	

end

rule "Determine Service Scenario 5"

when
	seoEventInstance:SeoEvent(MessageTypeEnum.INSTRUMENTATION == messageType);
then
	serviceName="Service3";	
		
end